### ISSUE TITLE
yotta upload or flash command?

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/yotta#532] opened 2015-10-25 09:17 UTC
I'm not sure if this is the domain of yotta or not. Feel close to close if it isn't

**Comment by BlackstoneEngineering** [comment] 2015-10-25 19:14
try `yotta debug`

**Comment by jrobeson** [comment] 2015-10-25 21:06
I have my own command to flash the devices. It uses udisksctl to find the devices and then simply copies it. I just wanted to know if a direct flash command will be added to yotta or not.

**Comment by BlackstoneEngineering** [comment] 2015-10-25 22:35
No, there are other tools that do this, such as exporting to external toolchains with [valinor](https://github.com/ARMmbed/valinor), or using the [mbed-greentea](https://github.com/ARMmbed/greentea) test bench integrator

**Comment by jrobeson** [comment] 2015-10-25 22:40
external toolchains with valinor? Isn't that what I have already when I"m using yotta?

**Comment by 0xc0170** [comment] 2015-10-26 08:33
@jrobeson You are talking about mbed devices which have an interface chip on board with virtual drive, what about a device outside of mbed ? 

Have you tried yotta debug? Do you find it limiting or see an improvements? Share with us

There are many diff ways to flash a device - some IDE does not have that support to flash a device via a command line, or have some limitations (IAR I am pointing to you :-)) or require a configuration file (openOCD) or just work outside of the box but for limited number of devices (pyOCD) or which works only with jlink but for almost any device (jlinkgdb).

**Comment by jrobeson** [comment] 2015-10-26 09:32
I'd assume initial support for mbed boards (where the usb drive shows up), and then jlink.

**Comment by autopulated** [comment] 2015-10-26 12:40
I think there is a place for `yotta run`, which mbed / embedded targets could interpret as being "upload and run". `yotta test` works the same way, for example. I'm closing this as a duplicate of #109

**Closed by autopulated** 2015-10-26 12:40 UTC
Labels: duplicate, enhancement
