### ISSUE TITLE
Assert on Derivative Target

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#650] opened 2016-01-09 09:38 UTC
## Problem
I cannot build the https://github.com/ARMmbed/mbed-client-linux-example on my linux machine

## More Info
I am running an Arch Linux machine, logged into the private registry.
Yotta version is the latest at `0.12.2`
System Info : `Linux  4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

## The steps to reproduce the error
```shell
git clone https://github.com/ARMmbed/mbed-client-linux-example
cd mbed-client-linux-example
yt target x86-linux-native
yt build
```

The build fails. When I try to run `yt target` i get the following output
```shell
yt target
Fatal Exception, yotta=0.12.2
Traceback (most recent call last):
  File "/usr/bin//yt", line 4, in <module>
    yotta.main()
  File "/usr/lib/python3.5/site-packages/yotta/main.py", line 205, in main
    status = args.command(args, following_args)
  File "/usr/lib/python3.5/site-packages/yotta/target.py", line 100, in execCommand
    return displayCurrentTarget(args)
  File "/usr/lib/python3.5/site-packages/yotta/target.py", line 66, in displayCurrentTarget
    args.target, c.targetsPath(), application_dir=app_path, install_missing=False
  File "/usr/lib/python3.5/site-packages/yotta/lib/target.py", line 155, in getDerivedTarget
    assert(isinstance(t, Target))
AssertionError
```
A gist of the build output can be seen here : https://gist.github.com/BlackstoneEngineering/7732f0b3fd3de145c84b#file-yotta-issue-650-gist-md 

## Solution
Unknown. I expected these steps to work and they ar not. This may be an invalid issue, but figured I should report it.

**Comment by autopulated** [comment] 2016-01-10 11:11
This is a duplicate of #643, thanks for noting that it's occurring for you, too. I plan to fix it in a patch release soon!

**Closed by autopulated** 2016-01-10 11:11 UTC
